exclude: ^(\+kwave/\+legacy/|\+kwave/site/|\.all-contributorsrc$)

repos:
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.1
    hooks:
      - id: prettier
        exclude: ^\+kwave/docs
        exclude_types: [markdown]
        args:
          - --quote-props=as-needed
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: no-commit-to-branch
        args:
          - --branch=main
          - --branch=develop
      - id: trailing-whitespace
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
