site_name: k-Wave-II

plugins:
  - search
  - literate-nav

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
nav:
  - Home: index.md
  - About:
    - Licence: LICENSE.md
  - Help: helpfilesweb/
  - Developer docs:
    - Intro: developerIntroduction.md
    - Standard: codingStandard.md
    - Class example: helpfilesweb/classDocsExample.md
  
theme: readthedocs