site_name: k-Wave-II

plugins:
  - search
  - literate-nav

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
nav:
  - Home: index.md
  - Contributor guidelines: CONTRIBUTING.md
  - Core Contributors: CONTRIBUTORS.md
  - Licence: LICENSE.md
  - How to:
    - Tutorials: helpfilesweb/Tutorials/
  - Code reference:
    - Toolbox Functions: helpfilesweb/Toolbox_Functions/
    - Utility Functions: helpfilesweb/Utility_Functions/
  - Developer docs:
    - Developer intro: developerIntroduction.md
    - Coding Standard: codingStandard.md
    - Template Class: helpfilesweb/classDocsExample.md
    - Maintainer guidelines: maintainerDocs.md
    - Test Functions: helpfilesweb/Test_Functions/
    - Developer Tools : helpfilesweb/Developer_Tools/
  
theme: readthedocs