%% TestElectromagneticSource
% *Package:* kwave.tests.unit
% *Superclasses:* kwave.tests.unit.AbstractTestGridInput
%
% Unit tests for the ElectromagneticSource class using the AbstractTestGridInput
% class.

classdef TestElectromagneticSource < kwave.tests.unit.AbstractTestGridInput

    properties
        inputClass = 'ElectromagneticSource'
        inputProperties = {...
            'initialElectricField', ...
            'initialMagneticField', ...
            'electricCurrentDensitySource', ...
            'magneticCurrentDensitySource'}
        inputPropertiesPadded = {...
            'initialElectricFieldPadded', ...
            'initialMagneticFieldPadded', ...
            'electricCurrentDensitySourcePadded', ...
            'magneticCurrentDensitySourcePadded'}
        inputPropertiesScalar = {}
        inputPropertiesComplex = {}
        inputPropertiesVectorField = {...
            'initialElectricField', ...
            'initialMagneticField', ...
            'electricCurrentDensitySource', ...
            'magneticCurrentDensitySource', ...
            'initialElectricFieldPadded', ....
            'initialMagneticFieldPadded', ...
            'electricCurrentDensitySourcePadded', ...
            'magneticCurrentDensitySourcePadded'}
    end

    methods(Test)
    end

end
