name: Checks code quality
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  matlab-tests:
    name: Run MATLAB Code Quality check
    runs-on: Windows
    if: github.event.pull_request.draft == false
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          matlab -batch "kwave.tests.runTests(testType='linting')"

      - name: Comment PR
        uses: mshick/add-pr-comment@v2
        with:
          message-path: |
            ./+kwave/+tests/linting-tests-artifacts/cyclomatic-complexity.txt
