name: Build docs
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - sp/49-deploy_gh_pages

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  matlab-docs:
    name: Build MATLAB docs
    runs-on: Windows
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build docs
        run: |
          & "C:\Program Files\MATLAB\R2025b\bin\matlab.exe" "-batch" "kwave.devtools.GenerateDocumentation"

      - name: Test docs
        shell: bash
        run: |
          source docs/test_doc_generation.sh

      - name: Upload helpfiles
        uses: actions/upload-artifact@v6
        with:
          name: docs-matlab
          path: docs


  docs:
    needs: matlab-docs
    name: Build Mkdocs docs
    runs-on: windows-latest
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Download helpfiles artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-matlab
          path: docs-matlab          

      - name: Rename docs-matlab to docs
        run: |
          mv docs-matlab docs

      - name: Build mkdocs
        run: |
          mkdocs build

      - name: Move helpfiles to site
        run: |
          mv helpfilesweb site/helpfilesweb

      - uses: actions/upload-pages-artifact@v4
        with:
          path: site

  deploy:
      needs: docs
      name: Deploy docs to GitHub Pages
      runs-on: ubuntu-latest
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4 