name: Run MATLAB tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  matlab-tests:
    name: Run unit tests
    runs-on: Windows
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          matlab -batch kwave.tests.runTests

      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./+kwave/+tests/unit-tests-artifacts/cobertura.xml
